services:
  api-server:
    container_name: api-server
    build:
      context: .
      dockerfile: ./apps/api-server/Dockerfile
    restart: always
    ports:
      - "5000:5000"
    networks:
      - app_network
  next-client:
    container_name: next-client
    build:
      context: .
      dockerfile: ./apps/next-client/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    networks:
      - app_network

networks:
  app_network:
    external: true