services:
  api-server:
    container_name: api-server
    build:
      context: .
      dockerfile: ./apps/api-server/Dockerfile
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: ./media
        target: /app/apps/api-server/media
    networks:
      - show_stream_network
  next-client:
    container_name: next-client
    build:
      context: .
      dockerfile: ./apps/next-client/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    networks:
      - show_stream_network
  mongodb:
    container_name: mongodb
    image: mongodb/mongodb-community-server:7.0-ubi8
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGODB_INITDB_ROOT_USERNAME: root
      MONGODB_INITDB_ROOT_PASSWORD: root
    volumes: 
      - type: bind
        source: ./data
        target: /data/db
    networks:
      - show_stream_network

networks:
  show_stream_network:
    external: true